AWSTemplateFormatVersion: 2010-09-09
Description: dltHub experiments AWS Lambda stack

Parameters:
  ArtifactsStackName:
    Type: String
  LambdaFunctionName:
    Type: String
    AllowedPattern: "[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+"
    Default: post-dlt-experiments

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !ImportValue 
          'Fn::Sub': '${ArtifactsStackName}-BucketName'
        S3Key: post-dlt-experiments.zip
      Description: post-dlt-experiments Function
      FunctionName: !Ref LambdaFunctionName
      Handler: func.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaIAMRole.Arn
      Runtime: python3.11
      Timeout: 60

  LambdaInboxRolePolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref LambdaIAMRole
      PolicyName: s3-inbox
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - s3:GetItem
            Effect: Allow
            Resource:
              - !GetAtt InboxBucket.Arn

  LambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*
        - PolicyName: s3-code
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                - s3:GetItem
                Effect: Allow
                Resource:
                  - !ImportValue 
                      'Fn::Sub': '${ArtifactsStackName}-BucketARN'

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}
      RetentionInDays: 5

  InboxBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationSettings: 
        - Event: s3:ObjectCreated:*
          Function: !Ref LambdaFunction

Outputs:
  LambdaArn:
    Value: !GetAtt LambdaFunction.Arn
  InboxBucketArn:
    Value: !GetAtt InboxBucket.Arn
